language: java

jdk:
  - openjdk8

sudo: required

services:
  - docker

before_install:
  - sudo apt-get install sshpass -y

install: true

script:
  - |
    if git diff HEAD~ --name-only|grep javaapp; then
      cd $TRAVIS_BUILD_DIR/javaapp/java-api
      docker login -u $DOCKER_USER -p $DOCKER_PASS
      mvn install dockerfile:build
      mvn  dockerfile:push
      sshpass -p $SERVER_PASS ssh $SERVER_USER@$SERVER_IP "sh komis/update_api.sh;"
    fi;