komis-db:
  container_name: komis-db
  image: postgres:9.4
  volumes:
    - ~/postgres/data:/var/lib/postgresql/data
  ports:
    - 5432:5432
komis-api:
  container_name: komis-api
  image: kowkowal/komisapi
  ports:
    - 8080:8080
  environment:
    - SPRING_PROFILES_ACTIVE=docker
    - PASS=PASS HERRE
  links:
    - komis-db:postgres